package Tela;

import Apoio.Formatacao;
import Controle.AnimalControle;
import Controle.ClienteControle;
import Controle.ServicoControle;
import Controle.TipoServicoControle;
import Entidade.Animal;
import Entidade.Cliente;
import Entidade.Servico;
import Entidade.TipoServico;
import java.util.List;
import javax.swing.JOptionPane;

public final class AdicionarServico extends javax.swing.JFrame {

    private List<TipoServico> listaServico;
    private List<Cliente> listaCliente;
    private List<Animal> listaAnimal;
    private ServicoTela servicoTela;

    private boolean verificadorListaServico = false;
    private boolean verificadorListaCliente = false;

    public AdicionarServico() {
        initComponents();
        Formatacao.formataHora(horario);
        Formatacao.formatarData(data);
        setarServicoNoCombo();
        setarClienteNoCombo();
        int idDono = this.setarClienteNoCombo();
        setarAnimais(idDono);
    }

    public AdicionarServico(List<Cliente> listaCliente, ServicoTela servicoTela) {
        initComponents();
        Formatacao.formataHora(horario);
        Formatacao.formatarData(data);
        this.listaCliente = listaCliente;
        setarServicoNoCombo();

        int idDono = this.setarClienteNoCombo();
        setarAnimais(idDono);
        this.servicoTela = servicoTela;
    }

    public void setarServicoNoCombo() {

        if (verificadorListaServico == false) {
            TipoServicoControle tsc = new TipoServicoControle();
            listaServico = tsc.listar(servico);
            verificadorListaServico = true;
        }

        TipoServico servicoSelecionado = listaServico.get(servico.getSelectedIndex());
        preco.setText(String.valueOf(servicoSelecionado.getValor()));

    }

    public int setarClienteNoCombo() {
        Cliente cliente = null;
        if (this.verificadorListaCliente == false) {
            ClienteControle cc = new ClienteControle();
            this.listaCliente = cc.listar(this.cliente);

            this.verificadorListaCliente = true;

            cliente = this.listaCliente.get(this.cliente.getSelectedIndex());

        } else {
            cliente = this.listaCliente.get(this.cliente.getSelectedIndex());
            this.setarAnimais(cliente.getId());
        }
        return cliente.getId();

    }

    public void setarAnimais(int idDono) {
        this.listaAnimal = null;
        AnimalControle ac = new AnimalControle();
        this.listaAnimal = ac.listar(idDono);

        String[] animais = new String[this.listaAnimal.size()];
        int cont = 0;
        for (Animal animal : this.listaAnimal) {
            animais[cont++] = animal.getNome();
        }

        this.animal.setModel(new javax.swing.DefaultComboBoxModel(animais));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        limpar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        cliente = new javax.swing.JComboBox();
        animal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        custo = new javax.swing.JComboBox();
        servico = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        data = new javax.swing.JFormattedTextField();
        horario = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Preço");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cliente");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Animal");

        limpar.setText("LIMPAR");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        cliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um cliente" }));
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        animal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um cliente acima" }));
        animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Horário");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Serviço");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Gasto");

        preco.setEditable(false);

        custo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "70%", "50%", "35%", "25%" }));
        custo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custoActionPerformed(evt);
            }
        });

        servico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um serviço" }));
        servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(animal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 13, Short.MAX_VALUE)
                                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(data)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addComponent(servico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(custo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(animal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrar)
                    .addComponent(limpar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(479, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed

        data.setText("");

    }//GEN-LAST:event_limparActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        AnimalControle ac = new AnimalControle();
        ServicoControle sc = new ServicoControle();
        ClienteControle cc = new ClienteControle();

        Animal animal = this.listaAnimal.get(this.animal.getSelectedIndex());
        TipoServico servico = this.listaServico.get(this.servico.getSelectedIndex());

        Servico s = new Servico();

        s.setData(data.getText());
        s.setHorario(horario.getText());

        char[] custoE = null;
        for (int i = 0; i < custo.getSelectedItem().toString().length(); i++) {
            custoE = custo.getSelectedItem().toString().toCharArray();
        }
        String custoC = "";
        for (int i = 0; i < 2; i++) {
            custoC += custoE[i];
        }

        float custoCorreto = (Float.parseFloat(preco.getText()) / 100) * Float.parseFloat(custoC);

        s.setCusto(custoCorreto);
        s.setPrecoServico(Float.parseFloat(preco.getText()));
        s.setId_animal(animal.getId());
        s.setNomeAnimal(animal.getNome());
        Cliente dono = cc.buscarUm(animal.getIdDono());
        s.setNomeDonoAnimal(dono.getNome());
        s.setId_tipoServico(servico.getId_servico());
        s.setNomeServico(servico.getNome());
        s.setFinalizado(false);
        sc.inserir(s);

        JOptionPane.showMessageDialog(null, "Serviço cadastrado com sucesso!");
        int dec = JOptionPane.showConfirmDialog(null, "Deseja adicionar outro serviço?");
        if (dec == 0) {

            data.setText("");

        } else {
            this.setVisible(false);
        }
        this.servicoTela.listarTabela();
    }//GEN-LAST:event_cadastrarActionPerformed

    private void custoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custoActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        this.setarClienteNoCombo();
    }//GEN-LAST:event_clienteActionPerformed

    private void servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicoActionPerformed
        this.setarServicoNoCombo();
    }//GEN-LAST:event_servicoActionPerformed

    private void animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox animal;
    private javax.swing.JButton cadastrar;
    private javax.swing.JComboBox cliente;
    private javax.swing.JComboBox custo;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JFormattedTextField horario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField preco;
    private javax.swing.JComboBox servico;
    // End of variables declaration//GEN-END:variables
}
