/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import DAO.CompraDAO;
import DAO.ItemCompraDAO;
import apoio.Formatacao;
import apoio.IItemPesquisa;
import entidade.Compra;
import entidade.ItemCompra;
import javax.swing.JOptionPane;

/**
 *
 * @author ander
 */
public class IfrCompra extends javax.swing.JInternalFrame implements IItemPesquisa {

    int idCompra = 0;
    double total = 0.0;

    /**
     * Creates new form IfrCompra
     */
    public IfrCompra() {
        initComponents();

        tffDataCom.setText(Formatacao.getDataAtual());

        tfdIdForn.setEditable(false);
        tfdNomeForn.setEditable(false);
        tfdTotal.setEditable(false);

        tfdIdProd.setEditable(false);
        tfdProd.setEditable(false);
        tfdValor.setEditable(false);

        btnLocalizarProd.setEnabled(false);
        btnRemover.setEnabled(false);
        btnInserir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdTotal = new javax.swing.JTextField();
        tfdProd = new javax.swing.JTextField();
        btnLocalizarProd = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        tfdValor = new javax.swing.JTextField();
        tfdIdProd = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tffDataCom = new javax.swing.JFormattedTextField();
        tfdQtde = new javax.swing.JTextField();
        tfdNomeForn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfdIdForn = new javax.swing.JTextField();
        btnLocalizarForn = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompra = new javax.swing.JTable();

        tfdTotal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tfdTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnLocalizarProd.setText("Localizar");
        btnLocalizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarProdActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        jLabel1.setText("Data");

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jLabel2.setText("Fornecedor");

        jLabel4.setText("Quantidade");

        tffDataCom.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("TOTAL");

        btnLocalizarForn.setText("Localizar");
        btnLocalizarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarFornActionPerformed(evt);
            }
        });

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        jLabel3.setText("Produto");

        tblCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ID Produto", "Descrição", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCompra);
        if (tblCompra.getColumnModel().getColumnCount() > 0) {
            tblCompra.getColumnModel().getColumn(0).setResizable(false);
            tblCompra.getColumnModel().getColumn(1).setResizable(false);
            tblCompra.getColumnModel().getColumn(2).setResizable(false);
            tblCompra.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCriar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFechar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfdQtde, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(tfdIdProd))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLocalizarProd))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tffDataCom)
                            .addComponent(tfdIdForn, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addComponent(tfdNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLocalizarForn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tffDataCom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdIdForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizarForn))
                .addGap(26, 26, 26)
                .addComponent(btnCriar)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizarProd)
                    .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnRemover)
                    .addComponent(jLabel4)
                    .addComponent(tfdQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(jLabel5)
                    .addComponent(tfdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocalizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarProdActionPerformed
        new DlgLocalizar(null, true, this, "produto").setVisible(true);
    }//GEN-LAST:event_btnLocalizarProdActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        ItemCompra itemCompra = new ItemCompra();

        itemCompra.setCompraId(idCompra);
        itemCompra.setProdutoId(Integer.parseInt(tfdIdProd.getText()));
        itemCompra.setQntde(Double.parseDouble(tfdQtde.getText()));
        itemCompra.setValor(Double.parseDouble(tfdValor.getText()));

        if (new ItemCompraDAO().salvar(itemCompra) == null) {
            JOptionPane.showMessageDialog(null, "Item inserido.");

            new ItemCompraDAO().popularTabela(tblCompra, "", idCompra);

            total += (itemCompra.getValor() * itemCompra.getQntde());

            tfdTotal.setText(String.valueOf(total));

            tfdIdProd.setText("");
            tfdProd.setText("");
            tfdValor.setText("");
            tfdQtde.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Erro na inserção.");
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (tblCompra.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro.");
        } else {
            int idItCom = Integer.parseInt(String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 0)));

            System.out.println("ItCom: " + idItCom);

            String retorno = new ItemCompraDAO().excluir(idItCom);

            if (retorno == null) {
                JOptionPane.showMessageDialog(null, "Registro remvodio.");

                double qtde = Double.parseDouble(String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 3)));
                double valor = Double.parseDouble(String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 4)));

                total -= (qtde * valor);

                tfdTotal.setText(String.valueOf(total));

                new ItemCompraDAO().popularTabela(tblCompra, "", idCompra);
            } else {
                JOptionPane.showMessageDialog(null, "Erro: Problemas ao remover registro.\n\n" + retorno);
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnLocalizarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarFornActionPerformed
        new DlgLocalizar(null, true, this, "fornecedor").setVisible(true);
    }//GEN-LAST:event_btnLocalizarFornActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed

        Compra Compra = new Compra();

        Compra.setData(tffDataCom.getText());
        Compra.setFornecedorId(Integer.parseInt(tfdIdForn.getText()));

        String retorno = new CompraDAO().salvar(Compra);

        System.out.println("Id Compra retorno: " + retorno);

        if (!retorno.contains("ERROR")) {
            idCompra = Integer.parseInt(retorno);

            btnCriar.setEnabled(false);
            btnLocalizarProd.setEnabled(true);
            btnRemover.setEnabled(true);
            btnInserir.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao criar Compra: " + retorno);
        }

    }

    @Override
    public void definirValor(String[] valores, String itemPesquisa) {
        if (itemPesquisa.equalsIgnoreCase("fornecedor")) {
            tfdIdForn.setText(valores[0]);
            tfdNomeForn.setText(valores[1]);
        } else if (itemPesquisa.equalsIgnoreCase("produto")) {
            tfdIdProd.setText(valores[0]);
            tfdProd.setText(valores[1]);
            tfdValor.setText(valores[2]);

        }
    }//GEN-LAST:event_btnCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLocalizarForn;
    private javax.swing.JButton btnLocalizarProd;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompra;
    private javax.swing.JTextField tfdIdForn;
    private javax.swing.JTextField tfdIdProd;
    private javax.swing.JTextField tfdNomeForn;
    private javax.swing.JTextField tfdProd;
    private javax.swing.JTextField tfdQtde;
    private javax.swing.JTextField tfdTotal;
    private javax.swing.JTextField tfdValor;
    private javax.swing.JFormattedTextField tffDataCom;
    // End of variables declaration//GEN-END:variables

}
