package tela;

// Imports controle.ControlaDisciplina e entidade.Disciplina
import controle.ControlaDisciplina;
import entidade.Disciplina;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfdCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaEmenta = new javax.swing.JTextArea();
        btnSair = new javax.swing.JButton();
        btnSalvarEmArquivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnSalvarEmArquivoNovo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Integrador - Univates");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Disciplinas - Uso de Arquivos");

        jLabel2.setText("Código");

        jLabel3.setText("Nome");

        jLabel4.setText("Ementa");

        txaEmenta.setColumns(20);
        txaEmenta.setRows(5);
        jScrollPane1.setViewportView(txaEmenta);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvarEmArquivo.setText("Salvar em arquivo");
        btnSalvarEmArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEmArquivoActionPerformed(evt);
            }
        });

        jLabel5.setText("Conteúdo do arquivo");

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Ementa"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        btnExcluir.setText("Excluir");
        btnExcluir.setName(""); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvarEmArquivoNovo.setText("Salvar Table em arquivo");
        btnSalvarEmArquivoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEmArquivoNovoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("* Alterar direto no Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSalvarEmArquivoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvarEmArquivo))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvarEmArquivo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnSalvarEmArquivoNovo))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // System.exit(0) - Finaliza o aplicativo
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarEmArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEmArquivoActionPerformed
        // Criando nova instância da classe Disciplina
        Disciplina d = new Disciplina();
        // Criando nova instância da classe ControlaDisciplina        
        ControlaDisciplina ctlDisciplina = new ControlaDisciplina();        
        
        // Verificar se todos os campos estão preenchidos
        if ( (tfdCodigo.getText().isEmpty()) || (tfdNome.getText().isEmpty()) || (txaEmenta.getText().isEmpty()) ) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
            // Posiciona cursor para próxima inserção
            tfdCodigo.requestFocus();
            // 'return' termina a execução do método por aqui
            return;
        }
        
        // Verificar se Codigo ou Nome Disciplina já estão cadastrados
        // Atribuímos a variável codigoConsulta o conteúdo digitado no tfdCodigo
        String codigoConsulta = tfdCodigo.getText();
        // Atribuímos a variável nomeConsulta o conteúdo digitado no tfdNome        
        String nomeConsulta = tfdNome.getText();
        // String conteúdo recebe retorno ctlDisciplina método consultar()
        String conteudo = ctlDisciplina.consultar(codigoConsulta, nomeConsulta); // conteúdo recebe retorno string de consultar()
        // Se conteudo está com "X" significa que Nome Disciplina já estava cadastrada
        if (conteudo == "X") {
            JOptionPane.showMessageDialog(null, "Esta disciplina já está cadastrada!");

            // posiciona cursor em tfdCodigo           
            tfdCodigo.requestFocus();   
            return;
        }        
        
        // Setando os valores para o objeto instanciado, a partir do JTextField e JTextArea
        d.setCodigo(Integer.parseInt(tfdCodigo.getText()));
        d.setNome(tfdNome.getText());
        d.setEmenta(txaEmenta.getText());

        // ctlDisciplina método salvar, recebendo como parâmetro 'Disciplina d' e 'anexar true'
        if (ctlDisciplina.salvar(d, true)) { // se salvar retornar true
            JOptionPane.showMessageDialog(null, "Registro adicionado com SUCESSO ao arquivo!");

            // Acrescentando o novo registro ao jTable
            // DefaultTableModel returns a column class of Object
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();   
            Object rowData[] = new Object[3]; 
            rowData[0] = tfdCodigo.getText();
            rowData[1] = tfdNome.getText();
            rowData[2] = txaEmenta.getText();
            table.addRow(rowData);   
            
            // limpa campos
            tfdCodigo.setText("");
            tfdNome.setText("");
            txaEmenta.setText("");

            // posiciona cursor para proxima insercao
            tfdCodigo.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Erro, problemas ao SALVAR em arquivo!");
        }

    }//GEN-LAST:event_btnSalvarEmArquivoActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // Criando nova instância objeto 'ctlDisciplina' do tipo ControlaDisciplina        
        ControlaDisciplina ctlDisciplina = new ControlaDisciplina();
        
        String codigoConsulta = ""; //ctrlDisciplina.consultar espera dois parâmetros
        String nomeConsulta = JOptionPane.showInputDialog("Digite parte do nome da disciplina a localizar");
                
        // String conteúdo recebe retorno ctlDisciplina método consultar()
        String conteudo = ctlDisciplina.consultar(codigoConsulta, nomeConsulta); // conteúdo recebe retorno string de consultar()

        // DefaultTableModel implementa a interface TableModel, 
        // fornecendo todo o controle dos dados da JTable.
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();          
        // Limpando a listagem anterior
        table.setRowCount(0);
        
        // Se String conteudo for diferente de vazio...
        if (conteudo != null) {              
            // Splitando o conteúdo em um Array de String
            String[] linhas = conteudo.split("\n");
            // Iterar sobre o array usando o loop for-each
            for(String disciplina: linhas){
                String disciplinaSplit[] = disciplina.split(";");
                // rowData - the data for the new table
                Object rowData[] = new Object[3]; 
                rowData[0] = disciplinaSplit[0];
                rowData[1] = disciplinaSplit[1];
                rowData[2] = disciplinaSplit[2];
                table.addRow(rowData);               
            }
            TableColumnModel columnModel = jTable1.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(10);
            columnModel.getColumn(1).setPreferredWidth(100);
            columnModel.getColumn(2).setPreferredWidth(200);            
        } else {
            JOptionPane.showMessageDialog(null, "Erro, consulta vazia!");
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    	DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        // Exibe caixa de diálogo solicitando confirmação ou não. 
        // Se o usuário clicar em "Sim" retorna 0 pra variável resposta, se informado não retorna 1
        int resposta = JOptionPane.showConfirmDialog(null, "Confirma a Exclusão da Disciplina?", "Excluir Disciplina", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {          
            table.removeRow(row);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarEmArquivoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEmArquivoNovoActionPerformed
        // TODO add your handling code here:
               
    	DefaultTableModel table = (DefaultTableModel) jTable1.getModel(); 
        // For passando por todas as linhas do jTable1
        for (int row = 0; row < table.getRowCount(); row++) {            
            // Criando nova instância da classe Disciplina
            Disciplina d = new Disciplina();
            // Criando nova instância da classe ControlaDisciplina         
            ControlaDisciplina ctlDisciplina = new ControlaDisciplina();  

            // Setando os valores para o objeto instanciado, a partir das colunas do jTable1
            d.setCodigo(Integer.parseInt(table.getValueAt(row, 0).toString()));
            d.setNome(table.getValueAt(row, 1).toString());
            d.setEmenta(table.getValueAt(row, 2).toString());
            
            // Apenas para a primeira linha do jTable1, as demais acrescenta...
            // ctlDisciplina método salvar, recebendo como parâmetro 'd' e 'anexar'
            if (row == 0) {        
                // anexar = false -> substitui conteúdo existente no arquivo
                if (!ctlDisciplina.salvar(d, false)) { // se salvar retornar false
                    JOptionPane.showMessageDialog(null, "Erro, problemas ao SALVAR em arquivo!");
                }
            } else {
                // anexar = true  -> preserva conteúdo existente, adicionando no final                
                if (!ctlDisciplina.salvar(d, true)) { // se salvar retornar false
                    JOptionPane.showMessageDialog(null, "Erro, problemas ao SALVAR em arquivo!");
                }                
            }
        }       
    }//GEN-LAST:event_btnSalvarEmArquivoNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarEmArquivo;
    private javax.swing.JButton btnSalvarEmArquivoNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfdCodigo;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextArea txaEmenta;
    // End of variables declaration//GEN-END:variables
}
